### ISSUE TITLE
demo can't run 

### ISSUE THREAD

**Issue by larryro** [thetatoken/theta-protocol-delivery-lib#2]
![image](https://user-images.githubusercontent.com/5787117/49698809-d2690700-fc03-11e8-9841-84e21992c987.png)
when run index.html on the demo.Video can not play and this error showed.

**Comment by jieyilong** [comment]
Thanks for reporting the issue. ThetaWebWidgets.js is a small file (about 11 kB). It could be just a hiccup. We have just verified that the demo worked. Could you try again? Thanks!

**Comment by larryro** [comment]
> dgets

Yes,it works,now.

**Comment by jieyilong** [comment]
OK thanks for the confirmation
